name: Deploy Docs

on:
  push:
    branches:
      - master
      - 3.x
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ubuntu-latest-11-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ubuntu-latest-11-gradle
      - name: Build aggregate Javadocs
        run: ./gradlew aggregateJavadoc
      - name: Deploy to GH Pages
        uses:
        with:
          name: test-results
          path: configurate-*/build/test-results/test
